PROGRAM=unicast

#EXTRA_CFLAGS+=-I../esp-gdbstub/include
#EXTRA_LDFLAGS+=-L../esp-gdbstub/lib
#CFLAGS+=-DportREMOVE_STATIC_QUALIFIER -DINCLUDE_pcTaskGetTaskName=1 -std=c99
EXTRA_COMPONENTS = extras/softuart

include ../common.mk

#LIBS+=esp-gdbstub
PROGRAM_CFLAGS+=-O0
